Repository sogno-platform/dpsim, pull requests merged in 2024-05, with the labels that each got.

#292 Fix VILLASnode in Dockerfiles
  packaging/Docker/Dockerfile.dev
  packaging/Docker/Dockerfile.dev-debian
  packaging/Docker/Dockerfile.manylinux
  packaging/Shell/install-fedora-deps-dev.sh
  packaging/Shell/install-fedora-deps.sh
  packaging/Shell/install-ubuntu-deps.sh
Labels: bug, dependencies

#296 Add new action using the build wrapper from sonar directly
  .github/workflows/sonar_cloud.yaml
  sonar-project.properties
Labels: enhancement, ci

#294 Enable compilation in gcc 14 and clang 18 (code fixes)
  dpsim-models/include/dpsim-models/DP/DP_Ph3_SynchronGeneratorDQ.h
  dpsim-models/include/dpsim-models/DP/DP_Ph3_SynchronGeneratorDQODE.h
  dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SynchronGeneratorDQ.h
  dpsim-models/include/dpsim-models/EMT/EMT_Ph3_SynchronGeneratorDQODE.h
  dpsim/examples/cxx/cim_graphviz/cimviz.cpp
  dpsim/include/dpsim/DAESolver.h
  dpsim/include/dpsim/DiakopticsSolver.h
  dpsim/src/DAESolver.cpp
Labels: enhancement
