Repository sogno-platform/dpsim, pull requests merged in 2025-04, with the labels that each got.

#353 fix(ci): Attempt to fix PyPi package publish
  .github/workflows/publish_to_pypi.yaml
Labels: ci, python

#351 Fix some capitalization
  .github/workflows/publish_to_pypi.yaml
Labels: enhancement, ci

#348 Move pytest.ini to pyproject.toml
  pyproject.toml
  pytest.ini
Labels: enhancement

#356 fix(cmake): Fix code-style
  cmake/FindGSL.cmake
  cmake/FindSundials.cmake
  dpsim-models/src/CMakeLists.txt
Labels: enhancement

#349 python: Harmonize comment style
  examples/Python/Base/test_async.py
  examples/Python/Circuits/test_circuit.py
  examples/Python/RuntimeMeas/decoupling_9bus_comp.py
  examples/Python/RuntimeMeas/decoupling_9bus_existing.py
  examples/Python/RuntimeMeas/decoupling_sched.py
  examples/Python/RuntimeMeas/diakoptics_splitsize.py
  examples/Python/RuntimeMeas/sched_nthreads.py
  examples/conftest.py
  examples/villas-deprecated/test_shmem_cigre_mv_pf_profiles.py
  examples/villas/dpsim-file.py
  examples/villas/dpsim-mqtt-cigre-mv-pf-profiles.py
  examples/villas/dpsim-mqtt-import-export-MIMO.py
  examples/villas/dpsim-mqtt-import-export.py
  python/src/dpsim/matpower.py
  setup.py
Labels: enhancement

#347 Remove outdated and broken GitLab CI pipeline
  .gitlab-ci.yml
Labels: ci

#352 Add pre-commit
  .github/workflows/pre_commit.yaml
  .pre-commit-config.yaml
  examples/Python/RuntimeMeas/meas_utils.py
  examples/villas/dpsim-mqtt-import-export-MIMO.py
  examples/villas/dpsim-mqtt.py
Labels: enhancement, ci

#355 Fix GitHub actions workflow for publishing to PyPi
  .github/workflows/build_test_linux_fedora.yaml
  .github/workflows/build_test_linux_fedora_minimal.yaml
  .github/workflows/build_test_linux_rocky.yaml
  .github/workflows/build_test_windows.yaml
  .github/workflows/publish_to_pypi.yaml
  .github/workflows/sonar_cloud.yaml
  packaging/Docker/Dockerfile.dev
  packaging/Docker/Dockerfile.dev-minimal
  packaging/Docker/Dockerfile.dev-rocky
  packaging/Docker/Dockerfile.manylinux
  setup.py
Labels: ci

#375 feat(ci): Use trusted / OIDC publishing to PyPi.org
  .github/workflows/publish_to_pypi.yaml
  pyproject.toml
Labels: ci, python, packaging

#362 Allow builds without nlohmann/json library
  dpsim/examples/cxx/CMakeLists.txt
  dpsim/include/dpsim/Config.h.in
  dpsim/include/dpsim/Simulation.h
  dpsim/include/dpsim/Utils.h
  dpsim/src/Utils.cpp
  dpsim/src/pybind/EMTComponents.cpp
Labels: enhancement, dependencies

#377 Add pre-commit /4
  .clang-format
  .pre-commit-config.yaml
  dpsim-models/include/dpsim-models/Components.h
  dpsim-models/include/dpsim-models/DP/DP_Ph1_ProfileVoltageSource.h
  dpsim-models/include/dpsim-models/EMT/EMT_Ph3_ControlledCurrentSource.h
  dpsim-models/include/dpsim-models/EMT/EMT_Ph3_ControlledVoltageSource.h
  dpsim-models/include/dpsim-models/EMT/EMT_Ph3_RXLoad.h
  dpsim-models/include/dpsim-models/Filesystem.h
  dpsim-models/include/dpsim-models/Logger.h
  dpsim-models/include/dpsim-models/MNAStampUtils.h
  dpsim-models/src/CIM/Reader.cpp
  dpsim-models/src/DP/DP_Ph1_ProfileVoltageSource.cpp
  dpsim-models/src/EMT/EMT_Ph1_Switch.cpp
  dpsim-models/src/EMT/EMT_Ph1_VoltageSource.cpp
  dpsim-models/src/EMT/EMT_Ph3_ControlledCurrentSource.cpp
  dpsim-models/src/EMT/EMT_Ph3_ControlledVoltageSource.cpp
  dpsim-models/src/EMT/EMT_Ph3_RXLoad.cpp
  dpsim-models/src/SimPowerComp.cpp
  dpsim-models/src/SystemTopology.cpp
  dpsim-villas/examples/cxx/Fpga9BusHil.cpp
  dpsim-villas/examples/cxx/FpgaCosim3PhInfiniteBus.cpp
  dpsim-villas/examples/cxx/FpgaCosimulation.cpp
  dpsim-villas/examples/cxx/FpgaExample.cpp
  dpsim/examples/cxx/CIM/DP_WSCC_9bus_split_decoupled.cpp
  dpsim/examples/cxx/CIM/EMT_WSCC-9bus_FullOrderSG.cpp
  dpsim/examples/cxx/CIM/EMT_WSCC_9bus_split_decoupled.cpp
  dpsim/examples/cxx/CIM/WSCC_9bus_mult_coupled.cpp
  dpsim/examples/cxx/CIM/WSCC_9bus_mult_decoupled.cpp
  dpsim/examples/cxx/CIM/WSCC_9bus_mult_diakoptics.cpp
  dpsim/include/dpsim/DataLogger.h
  dpsim/include/dpsim/DataLoggerInterface.h
  dpsim/include/dpsim/InterfaceQueued.h
  dpsim/include/dpsim/RealTimeDataLogger.h
  dpsim/include/dpsim/Simulation.h
  dpsim/src/DataLogger.cpp
  dpsim/src/InterfaceQueued.cpp
  dpsim/src/MNASolverPlugin.cpp
  dpsim/src/RealTimeDataLogger.cpp
  dpsim/src/RealTimeSimulation.cpp
  dpsim/src/pybind/DPComponents.cpp
  dpsim/src/pybind/EMTComponents.cpp
  dpsim/src/pybind/SPComponents.cpp
  dpsim/src/pybind/main.cpp
Labels: enhancement, refactor

#284 Revision of power flow solver
  dpsim-models/include/dpsim-models/SP/SP_Ph1_NetworkInjection.h
  dpsim-models/src/SP/SP_Ph1_Load.cpp
  dpsim-models/src/SP/SP_Ph1_NetworkInjection.cpp
  dpsim/src/PFSolver.cpp
  dpsim/src/PFSolverPowerPolar.cpp
Labels: enhancement

#380 Add support for CMake `find package` and rename "KLU" dependency to name of actual library "SuiteSparse"
  CMakeLists.txt
  cmake/FetchJson.cmake
  cmake/FetchJsonLibrary.cmake
  cmake/FetchReaderWriterQueue.cmake
  cmake/FetchSuiteSparse.cmake
  cmake/FindCIMpp.cmake
  cmake/FindSuiteSparse.cmake
  cmake/FindSundials.cmake
  dpsim/include/dpsim/MNASolverFactory.h
  dpsim/src/CMakeLists.txt
Labels: packaging

#376 Fix CMake typos and style
  CMakeLists.txt
  dpsim-villas/examples/cxx/CMakeLists.txt
  dpsim/examples/cxx/CMakeLists.txt
Labels: refactor, packaging

#386 Add pre-commit /8
  .pre-commit-config.yaml
  README.md
  docs/hugo/content/en/docs/Concepts/dyn-phasors.md
  docs/hugo/content/en/docs/Concepts/nodal-analysis.md
  docs/hugo/content/en/docs/Concepts/powerflow.md
  docs/hugo/content/en/docs/Development/Debugging.md
  docs/hugo/content/en/docs/Development/_index.md
  docs/hugo/content/en/docs/Development/debugging.md
  docs/hugo/content/en/docs/Development/guidelines.md
  docs/hugo/content/en/docs/Getting started/build.md
  docs/hugo/content/en/docs/Getting started/install.md
  docs/hugo/content/en/docs/Getting started/real-time.md
  docs/hugo/content/en/docs/Models/RLC-Elements/index.md
  docs/hugo/content/en/docs/Models/Synchronous Generator/index.md
  docs/hugo/content/en/docs/Models/Transformer/index.md
  docs/hugo/content/en/docs/Models/_index.md
  docs/hugo/content/en/docs/Models/branches.md
  docs/hugo/content/en/docs/Overview/Architecture/index.md
  docs/hugo/content/en/docs/Overview/Attributes/index.md
  docs/hugo/content/en/docs/Overview/_index.md
  docs/hugo/content/en/docs/Overview/interfaces.md
  docs/hugo/content/en/docs/Overview/mnainterface.md
  docs/hugo/content/en/docs/Overview/subcomponents.md
  docs/hugo/content/en/docs/Roadmap/index.md
  docs/hugo/content/en/docs/Tasks/add-model.md
  docs/hugo/content/en/docs/Tasks/create-simulation.md
  docs/hugo/content/en/docs/_index.md
Labels: documentation, ci, refactor

#388 Reduce attributes number
  dpsim-models/include/dpsim-models/Base/Base_Ph1_Transformer.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_AvVoltageSourceInverterDQ.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_Load.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_NetworkInjection.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_PiLine.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_RXLine.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_SynchronGenerator.h
  dpsim-models/include/dpsim-models/SP/SP_Ph1_Transformer.h
  dpsim-models/src/DP/DP_Ph1_Transformer.cpp
  dpsim-models/src/SP/SP_Ph1_AvVoltageSourceInverterDQ.cpp
  dpsim-models/src/SP/SP_Ph1_Load.cpp
  dpsim-models/src/SP/SP_Ph1_NetworkInjection.cpp
  dpsim-models/src/SP/SP_Ph1_PiLine.cpp
  dpsim-models/src/SP/SP_Ph1_RXLine.cpp
  dpsim-models/src/SP/SP_Ph1_SynchronGenerator.cpp
  dpsim-models/src/SP/SP_Ph1_Transformer.cpp
  dpsim/src/PFSolver.cpp
Labels: refactor

#357 Nix packaging
  .github/workflows/build_nix.yaml
  docs/hugo/content/en/docs/Getting started/build.md
  flake.lock
  flake.nix
  packaging/Nix/cimpp.nix
  packaging/Nix/dpsim.nix
  packaging/Nix/dpsimpy.nix
  packaging/Nix/readerwriterqueue.nix
  packaging/Nix/shell.nix
  packaging/Nix/suitesparse.nix
  packaging/Nix/sundials.nix
Labels: enhancement

#387 Upgrade Fedora dockerfiles to v42
  dpsim-models/src/SystemTopology.cpp
  dpsim/include/dpsim/Timer.h
  dpsim/src/KLUAdapter.cpp
  dpsim/src/Timer.cpp
  packaging/Docker/Dockerfile
  packaging/Docker/Dockerfile.dev
  packaging/Docker/Dockerfile.dev-minimal
Labels: enhancement
